language: ruby

rvm:
  - 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master

install:
  - gem install jekyll jekyll-redirect-from html-proofer
  - sudo pip install s3cmd

script:
  - jekyll build && htmlproofer ./_site
  - s3cmd sync --delete-removed _site/ s3://warehaus.io/ --verbose
