language: ruby

rvm:
  - 2.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master

install:
  - gem install jekyll jekyll-redirect-from
  - sudo pip install s3cmd

script:
  - jekyll build && s3cmd sync --force --guess-mime-type --delete-removed _site/ s3://warehaus.io/ --verbose
