# Site settings
title: Warehaus
email: hi@warehaus.io
description: >
  Warehaus configuration management tool
baseurl: ""
url: "https://warehaus.io"

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
